//Defining Action Types for Detailed Disney+Hotstar data
export const disneyActionTypes = {
  FETCH_DISNEY_MOVIE_LANGUAGE: "FETCH_DISNEY_MOVIE_LANGUAGE",
  FETCH_DISNEY_MOVIE_GENRE: "FETCH_DISNEY_MOVIE_GENRE",
  FETCH_DISNEY_SERIES_LANGUAGE: "FETCH_DISNEY_SERIES_LANGUAGE",
  FETCH_DISNEY_SERIES_GENRE: "FETCH_DISNEY_SERIES_GENRE",
};
