//Defining Action Types for Detailed Netflix data
export const netflixActionTypes = {
  FETCH_NETFLIX_MOVIE_LANGUAGE: "FETCH_NETFLIX_MOVIE_LANGUAGE",
  FETCH_NETFLIX_MOVIE_GENRE: "FETCH_NETFLIX_MOVIE_GENRE",
  FETCH_NETFLIX_SERIES_LANGUAGE: "FETCH_NETFLIX_SERIES_LANGUAGE",
  FETCH_NETFLIX_SERIES_GENRE: "FETCH_NETFLIX_SERIES_GENRE",
  FETCH_NETFLIX_MAP: "FETCH_NETFLIX_MAP",
};
