//Defining Action types for Recommender
export const recommenderActions = {
  RECOMMENDER_SUCCESS: "RECOMMENDER_SUCCESS",
  RECOMMENDER_ERROR: "RECOMMENDER_ERROR",
  RECOMMENDER_PROCESSING: "RECOMMENDER_PROCESSING",
  RECOMMENDER_RESET: "RECOMMENDER_RESET",
};
