//Defining Action Types for Detailed Prime Videos data
export const primeActionTypes = {
  FETCH_PRIME_MOVIE_LANGUAGE: "FETCH_PRIME_MOVIE_LANGUAGE",
  FETCH_PRIME_MOVIE_GENRE: "FETCH_PRIME_MOVIE_GENRE",
  FETCH_PRIME_SERIES_LANGUAGE: "FETCH_PRIME_SERIES_LANGUAGE",
  FETCH_PRIME_SERIES_GENRE: "FETCH_PRIME_SERIES_GENRE",
};
